# This workflow will build and push a web application to an Azure Static Web App when you change your code.
#
# This workflow assumes you have already created the target Azure Static Web App.
# For instructions see https://docs.microsoft.com/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_STATIC_WEB_APPS_API_TOKEN with the value of your Static Web Apps deployment token.
#    For instructions on obtaining the deployment token see: https://docs.microsoft.com/azure/static-web-apps/deployment-token-management
#
# 3. Change the values for the APP_LOCATION, API_LOCATION and APP_ARTIFACT_LOCATION, AZURE_STATIC_WEB_APPS_API_TOKEN environment variables (below).
#    For instructions on setting up the appropriate configuration values go to https://docs.microsoft.com/azure/static-web-apps/front-end-frameworks
name: Deploy web app to AWS S3

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

# Environment variables available to all jobs and steps in this workflow
env:
  AWS_REGION: ap-southeast-1
  AWS_ACCESS_KEY_ID: "AKIAU6GD3UDDDBMFFF6W"
  AWS_SECRET_ACCESS_KEY: "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"

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: write # for Azure/static-web-apps-deploy to comment on PRs
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
          
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Install Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '18.x'
        
      - name: Install Yarn
        run: npm install -g yarn
        
      - name: Install Dependency
        working-directory: sgevent-ui
        run: yarn install
        
      - name: Build
        working-directory: sgevent-ui
        run: yarn build
      
      - name: Verify build
        working-directory: sgevent-ui
        run: ls -la public
        
      - name: Deploy to S3
        working-directory: sgevent-ui
        run: gatsby-plugin-s3 deploy

  
